### ISSUE TITLE
Improved dependency documentation

### ISSUE THREAD

**Issue by Synaps3** [rpanfili/airQualityMeter#4]
Hey rpanfili,

Tried to get this to build and couldn't. I'm a novice with vs code and C++ isn't my preferred language so I'm sure that doesn't help.

It's not clear to me which versions of your dependencies I should install or if any of them have broken since your last commit.  It's also not clear to me how vs code does its dependency management. Is it global scope or do dependencies need to be added specifically to a project after being installed?

Anyway the litany of errors we get indicates dependency problems, and your how-to glosses completely over that so we're unable to make use of your nice project.

Could you please add detailed versioning and dependency management requirements, with a particular IDE in mind? That would help a lot of newbies.

Thanks.

**Comment by rpanfili** [comment]
Hello there :)
You are right and, since ArduinoJson v6 library is out, you get build issues.
I just added a new commit and [this](https://github.com/rpanfili/airQualityMeter/commit/eac6c8b352ea34d400d5c825c46cf1271ad860c7) fix that issue, locking dependencies to a compatible version!
Overall the building phase is pretty simple if you use PlatformIO because it will take care of all dependencies for you. Now you have just to press the "build" button and it should work without issues.
Reopen this issue if this changes don't fix the problem for you! (and help me understand what's failing attaching the output of that build process on platformIO)
